### PR TITLE
Auto Fetch wether without press button

### PR DESCRIPTION
**Pull request by PhantasWeng**
As title.

1. Save button context on appeared
2. Send getGlobalSettings action when `willAppear`
3. Make **getGlobalSettings** to a single function
4. Wrap check value and send response to a **getWeather** function
5. Auto refetch wether when setting changed

---
This PR also solve [Time Interval Fetch Still Requires Initial Button Push #40](https://github.com/JaouherK/streamDeck-weatherPlugin/issues/40)

### CODE REVIEW

**Review by JaouherK — COMMENTED** [review]
LGTM. A small change is required and I will add my changes to it later.
Thank you @PhantasWeng

**Comment by PhantasWeng** [comment]
got it, i will fix it asap.

**Comment by JaouherK** [comment]
@PhantasWeng Thanks a lot. the merge has been done. will add to it some changes I was working on and this should be visible in the next release :)
🥇

**Comment by PhantasWeng** [comment]
Thanks! glad to contribute.

**Pull request merged**
